blank_issues_enabled: false
contact_links:
  - name: Stacked Linear PyTorch Issues
    url: https://github.com/moinfar/stacked-linear/issues
    about: If you have questions or need help with “How to do X”, please ask them here.
